/*
 * Copyright (C)  Eric Yang <eric_yang@accton.com>
 *
 * This module supports the accton fpga via pcie that read/write reg
 * mechanism to get OSFP/SFP status ...etc.
 * This includes the:
 *     Accton as1813_128 FPGA
 *
 * Copyright (C) 2017 Finisar Corp.
 *
 * This file is licensed under the terms of the GNU General Public
 * License version 2. This program is licensed "as is" without any
 * warranty of any kind, whether express or implied.
 */

#include <linux/module.h>
#include <linux/init.h>
#include <linux/slab.h>
#include <linux/device.h>
#include <linux/platform_device.h>
#include <linux/i2c.h>
#include <linux/mutex.h>
#include <linux/interrupt.h>
#include <linux/i2c-mux.h>
#include <linux/version.h>
#include <linux/stat.h>
#include <linux/hwmon-sysfs.h>
#include <linux/delay.h>
#include <linux/pci.h>
#include <linux/time64.h>

#define __STDC_WANT_LIB_EXT1__ 1
#include <linux/string.h>
#include <linux/platform_data/i2c-ocores.h>

/***********************************************
 *       variable define
 * *********************************************/
#define DRVNAME                        "as1813_128_fpga"
#define OCORES_I2C_DRVNAME             "ocores-as1813"

#define PORT_NUM                       130 /* 128 OSFPs 2 SFPs*/
/*
 * PCIE BAR address
 */
#define BAR0_NUM                       0
#define FPGA_PCI_VENDOR_ID             0x10ee
#define FPGA_PCI_DEVICE_ID             0x7021
#define FPGA_PCIE_START_OFFSET         0x0000
#define FPGA_MAJOR_VER_REG             0x01
#define FPGA_MINOR_VER_REG             0x02
#define SPI_BUSY_MASK_CPLD            0x01
#define FPGA_BOARD_INFO_REG            (FPGA_PCIE_START_OFFSET + 0x00)
/* CPLD */
#define CPLD_PCIE_START_OFFSET         0x2000
/*FPGA SPI*/
#define SPI_MUX_REG                    0x2F00
#define SPI_BUSY_REG                   0x33

/* MEZZ TOP_L, spi_mux_ Region 0, 8'h04: pcie to Mezz_TOP_L */
#define XCVR_P8_P1_RESET_REG        (CPLD_PCIE_START_OFFSET + 0x78)
#define XCVR_P16_P9_RESET_REG       (CPLD_PCIE_START_OFFSET + 0x79)
#define XCVR_P8_P1_LPMODE_REG       (CPLD_PCIE_START_OFFSET + 0x70)
#define XCVR_P16_P9_LPMODE_REG      (CPLD_PCIE_START_OFFSET + 0x71)
#define XCVR_P8_P1_PRESENT_REG      (CPLD_PCIE_START_OFFSET + 0x88)
#define XCVR_P16_P9_PRESENT_REG     (CPLD_PCIE_START_OFFSET + 0x89)
/* MEZZ TOP_R, spi_mux_ Region 0, 8'h05: pcie to Mezz_TOP_R */
#define XCVR_P24_P17_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x78)
#define XCVR_P32_P25_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x79)
#define XCVR_P24_P17_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x70)
#define XCVR_P32_P25_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x71)
#define XCVR_P24_P17_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x88)
#define XCVR_P32_P25_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x89)
/* MB CPLD0, spi_mux_ Region 0, 8'h00: pcie to MB CPLD0 */
#define XCVR_P36_P33_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x78)
#define XCVR_P40_P37_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x79)
#define XCVR_P44_P41_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x7A)
#define XCVR_P48_P45_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x7B)
#define XCVR_P36_P33_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x70)
#define XCVR_P40_P37_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x71)
#define XCVR_P44_P41_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x72)
#define XCVR_P48_P45_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x73)
#define XCVR_P36_P33_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x88)
#define XCVR_P40_P37_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x89)
#define XCVR_P44_P41_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x8A)
#define XCVR_P48_P45_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x8B)
/* MB CPLD1, spi_mux_ Region 0, 8'h01: pcie to MB CPLD1 */
#define XCVR_P52_P49_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x78)
#define XCVR_P56_P53_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x79)
#define XCVR_P60_P57_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x7A)
#define XCVR_P64_P61_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x7B)
#define XCVR_P52_P49_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x70)
#define XCVR_P56_P53_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x71)
#define XCVR_P60_P57_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x72)
#define XCVR_P64_P61_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x73)
#define XCVR_P52_P49_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x88)
#define XCVR_P56_P53_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x89)
#define XCVR_P60_P57_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x8A)
#define XCVR_P64_P61_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x8B)
/* MB CPLD0, spi_mux_ Region 0, 8'h00: pcie to MB CPLD0 */
#define XCVR_P68_P65_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x78)
#define XCVR_P72_P69_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x79)
#define XCVR_P76_P73_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x7A)
#define XCVR_P80_P77_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x7B)
#define XCVR_P68_P65_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x70)
#define XCVR_P72_P69_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x71)
#define XCVR_P76_P73_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x72)
#define XCVR_P80_P77_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x73)
#define XCVR_P68_P65_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x88)
#define XCVR_P72_P69_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x89)
#define XCVR_P76_P73_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x8A)
#define XCVR_P80_P77_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x8B)
/* MB CPLD1, spi_mux_ Region 0, 8'h01: pcie to MB CPLD1 */
#define XCVR_P84_P81_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x78)
#define XCVR_P88_P85_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x79)
#define XCVR_P92_P89_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x7A)
#define XCVR_P96_P93_RESET_REG      (CPLD_PCIE_START_OFFSET + 0x7B)
#define XCVR_P84_P81_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x70)
#define XCVR_P88_P85_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x71)
#define XCVR_P92_P89_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x72)
#define XCVR_P96_P93_LPMODE_REG     (CPLD_PCIE_START_OFFSET + 0x73)
#define XCVR_P84_P81_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x88)
#define XCVR_P88_P85_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x89)
#define XCVR_P92_P89_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x8A)
#define XCVR_P96_P93_PRESENT_REG    (CPLD_PCIE_START_OFFSET + 0x8B)
/* MEZZ BOT_L, spi_mux_ Region 0, 8'h02: pcie to Mezz_BOT_L */
#define XCVR_P104_P97_RESET_REG     (CPLD_PCIE_START_OFFSET + 0x78)
#define XCVR_P112_P105_RESET_REG    (CPLD_PCIE_START_OFFSET + 0x79)
#define XCVR_P104_P97_LPMODE_REG    (CPLD_PCIE_START_OFFSET + 0x70)
#define XCVR_P112_P105_LPMODE_REG   (CPLD_PCIE_START_OFFSET + 0x71)
#define XCVR_P104_P97_PRESENT_REG   (CPLD_PCIE_START_OFFSET + 0x88)
#define XCVR_P112_P105_PRESENT_REG  (CPLD_PCIE_START_OFFSET + 0x89)
/* MEZZ BOT_R, spi_mux_ Region 0, 8'h03: pcie to Mezz_BOT_R */
#define XCVR_P120_P113_RESET_REG    (CPLD_PCIE_START_OFFSET + 0x78)
#define XCVR_P128_P121_RESET_REG    (CPLD_PCIE_START_OFFSET + 0x79)
#define XCVR_P120_P113_LPMODE_REG   (CPLD_PCIE_START_OFFSET + 0x70)
#define XCVR_P128_P121_LPMODE_REG   (CPLD_PCIE_START_OFFSET + 0x71)
#define XCVR_P120_P113_PRESENT_REG  (CPLD_PCIE_START_OFFSET + 0x88)
#define XCVR_P128_P121_PRESENT_REG  (CPLD_PCIE_START_OFFSET + 0x89)
/* MB CPLD1, spi_mux_ Region 0, 8'h01: pcie to MB CPLD1 */
#define XCVR_P130_P129_PRESENT_REG  (CPLD_PCIE_START_OFFSET + 0x28)
#define XCVR_P130_P129_TXDIS_REG    (CPLD_PCIE_START_OFFSET + 0x18)
#define XCVR_P130_P129_RXLOS_REG    (CPLD_PCIE_START_OFFSET + 0x20)
#define XCVR_P130_P129_TXFAULT_REG  (CPLD_PCIE_START_OFFSET + 0x10)

#define TRANSCEIVER_PRESENT_ATTR_ID(index)    MODULE_PRESENT_##index
#define TRANSCEIVER_LPMODE_ATTR_ID(index)     MODULE_LPMODE_##index
#define TRANSCEIVER_RESET_ATTR_ID(index)      MODULE_RESET_##index
#define TRANSCEIVER_TX_DISABLE_ATTR_ID(index) MODULE_TX_DISABLE_##index
#define TRANSCEIVER_TX_FAULT_ATTR_ID(index)   MODULE_TX_FAULT_##index
#define TRANSCEIVER_RX_LOS_ATTR_ID(index)     MODULE_RX_LOS_##index
/***********************************************
 *       macro define
 * *********************************************/
#define pcie_err(fmt, args...) \
        printk(KERN_ERR "["DRVNAME"]: " fmt " ", ##args)

#define pcie_info(fmt, args...) \
        printk(KERN_ERR "["DRVNAME"]: " fmt " ", ##args)


#define LOCK(lock)      \
do {                                                \
    spin_lock(lock);                                \
} while (0)

#define UNLOCK(lock)    \
do {                                                \
    spin_unlock(lock);                              \
} while (0)


/***********************************************
 *       structure & variable declare
 * *********************************************/
typedef struct pci_fpga_device_s {
    void  __iomem *data_base_addr0;
    struct pci_dev  *pci_dev;
    struct platform_device *fpga_i2c[PORT_NUM];
} pci_fpga_device_t;

/*fpga port status*/
struct as1813_128_fpga_data {
    u8                  cpld_reg[2];
    unsigned long       last_updated;    /* In jiffies */
    pci_fpga_device_t   pci_fpga_dev;
};

static struct platform_device *pdev = NULL;
extern spinlock_t cpld_access_lock;
extern int wait_spi(u32 mask, unsigned long timeout);
extern void __iomem *spi_busy_reg;
extern void __iomem *spi_mux_reg;
/***********************************************
 *       enum define
 * *********************************************/
enum fpga_sysfs_attributes {
    /* transceiver attributes */
    TRANSCEIVER_PRESENT_ATTR_ID(1),
    TRANSCEIVER_PRESENT_ATTR_ID(2),
    TRANSCEIVER_PRESENT_ATTR_ID(3),
    TRANSCEIVER_PRESENT_ATTR_ID(4),
    TRANSCEIVER_PRESENT_ATTR_ID(5),
    TRANSCEIVER_PRESENT_ATTR_ID(6),
    TRANSCEIVER_PRESENT_ATTR_ID(7),
    TRANSCEIVER_PRESENT_ATTR_ID(8),
    TRANSCEIVER_PRESENT_ATTR_ID(9),
    TRANSCEIVER_PRESENT_ATTR_ID(10),
    TRANSCEIVER_PRESENT_ATTR_ID(11),
    TRANSCEIVER_PRESENT_ATTR_ID(12),
    TRANSCEIVER_PRESENT_ATTR_ID(13),
    TRANSCEIVER_PRESENT_ATTR_ID(14),
    TRANSCEIVER_PRESENT_ATTR_ID(15),
    TRANSCEIVER_PRESENT_ATTR_ID(16),
    TRANSCEIVER_PRESENT_ATTR_ID(17),
    TRANSCEIVER_PRESENT_ATTR_ID(18),
    TRANSCEIVER_PRESENT_ATTR_ID(19),
    TRANSCEIVER_PRESENT_ATTR_ID(20),
    TRANSCEIVER_PRESENT_ATTR_ID(21),
    TRANSCEIVER_PRESENT_ATTR_ID(22),
    TRANSCEIVER_PRESENT_ATTR_ID(23),
    TRANSCEIVER_PRESENT_ATTR_ID(24),
    TRANSCEIVER_PRESENT_ATTR_ID(25),
    TRANSCEIVER_PRESENT_ATTR_ID(26),
    TRANSCEIVER_PRESENT_ATTR_ID(27),
    TRANSCEIVER_PRESENT_ATTR_ID(28),
    TRANSCEIVER_PRESENT_ATTR_ID(29),
    TRANSCEIVER_PRESENT_ATTR_ID(30),
    TRANSCEIVER_PRESENT_ATTR_ID(31),
    TRANSCEIVER_PRESENT_ATTR_ID(32),
    TRANSCEIVER_PRESENT_ATTR_ID(33),
    TRANSCEIVER_PRESENT_ATTR_ID(34),
    TRANSCEIVER_PRESENT_ATTR_ID(35),
    TRANSCEIVER_PRESENT_ATTR_ID(36),
    TRANSCEIVER_PRESENT_ATTR_ID(37),
    TRANSCEIVER_PRESENT_ATTR_ID(38),
    TRANSCEIVER_PRESENT_ATTR_ID(39),
    TRANSCEIVER_PRESENT_ATTR_ID(40),
    TRANSCEIVER_PRESENT_ATTR_ID(41),
    TRANSCEIVER_PRESENT_ATTR_ID(42),
    TRANSCEIVER_PRESENT_ATTR_ID(43),
    TRANSCEIVER_PRESENT_ATTR_ID(44),
    TRANSCEIVER_PRESENT_ATTR_ID(45),
    TRANSCEIVER_PRESENT_ATTR_ID(46),
    TRANSCEIVER_PRESENT_ATTR_ID(47),
    TRANSCEIVER_PRESENT_ATTR_ID(48),
    TRANSCEIVER_PRESENT_ATTR_ID(49),
    TRANSCEIVER_PRESENT_ATTR_ID(50),
    TRANSCEIVER_PRESENT_ATTR_ID(51),
    TRANSCEIVER_PRESENT_ATTR_ID(52),
    TRANSCEIVER_PRESENT_ATTR_ID(53),
    TRANSCEIVER_PRESENT_ATTR_ID(54),
    TRANSCEIVER_PRESENT_ATTR_ID(55),
    TRANSCEIVER_PRESENT_ATTR_ID(56),
    TRANSCEIVER_PRESENT_ATTR_ID(57),
    TRANSCEIVER_PRESENT_ATTR_ID(58),
    TRANSCEIVER_PRESENT_ATTR_ID(59),
    TRANSCEIVER_PRESENT_ATTR_ID(60),
    TRANSCEIVER_PRESENT_ATTR_ID(61),
    TRANSCEIVER_PRESENT_ATTR_ID(62),
    TRANSCEIVER_PRESENT_ATTR_ID(63),
    TRANSCEIVER_PRESENT_ATTR_ID(64),
    TRANSCEIVER_PRESENT_ATTR_ID(65),
    TRANSCEIVER_PRESENT_ATTR_ID(66),
    TRANSCEIVER_PRESENT_ATTR_ID(67),
    TRANSCEIVER_PRESENT_ATTR_ID(68),
    TRANSCEIVER_PRESENT_ATTR_ID(69),
    TRANSCEIVER_PRESENT_ATTR_ID(70),
    TRANSCEIVER_PRESENT_ATTR_ID(71),
    TRANSCEIVER_PRESENT_ATTR_ID(72),
    TRANSCEIVER_PRESENT_ATTR_ID(73),
    TRANSCEIVER_PRESENT_ATTR_ID(74),
    TRANSCEIVER_PRESENT_ATTR_ID(75),
    TRANSCEIVER_PRESENT_ATTR_ID(76),
    TRANSCEIVER_PRESENT_ATTR_ID(77),
    TRANSCEIVER_PRESENT_ATTR_ID(78),
    TRANSCEIVER_PRESENT_ATTR_ID(79),
    TRANSCEIVER_PRESENT_ATTR_ID(80),
    TRANSCEIVER_PRESENT_ATTR_ID(81),
    TRANSCEIVER_PRESENT_ATTR_ID(82),
    TRANSCEIVER_PRESENT_ATTR_ID(83),
    TRANSCEIVER_PRESENT_ATTR_ID(84),
    TRANSCEIVER_PRESENT_ATTR_ID(85),
    TRANSCEIVER_PRESENT_ATTR_ID(86),
    TRANSCEIVER_PRESENT_ATTR_ID(87),
    TRANSCEIVER_PRESENT_ATTR_ID(88),
    TRANSCEIVER_PRESENT_ATTR_ID(89),
    TRANSCEIVER_PRESENT_ATTR_ID(90),
    TRANSCEIVER_PRESENT_ATTR_ID(91),
    TRANSCEIVER_PRESENT_ATTR_ID(92),
    TRANSCEIVER_PRESENT_ATTR_ID(93),
    TRANSCEIVER_PRESENT_ATTR_ID(94),
    TRANSCEIVER_PRESENT_ATTR_ID(95),
    TRANSCEIVER_PRESENT_ATTR_ID(96),
    TRANSCEIVER_PRESENT_ATTR_ID(97),
    TRANSCEIVER_PRESENT_ATTR_ID(98),
    TRANSCEIVER_PRESENT_ATTR_ID(99),
    TRANSCEIVER_PRESENT_ATTR_ID(100),
    TRANSCEIVER_PRESENT_ATTR_ID(101),
    TRANSCEIVER_PRESENT_ATTR_ID(102),
    TRANSCEIVER_PRESENT_ATTR_ID(103),
    TRANSCEIVER_PRESENT_ATTR_ID(104),
    TRANSCEIVER_PRESENT_ATTR_ID(105),
    TRANSCEIVER_PRESENT_ATTR_ID(106),
    TRANSCEIVER_PRESENT_ATTR_ID(107),
    TRANSCEIVER_PRESENT_ATTR_ID(108),
    TRANSCEIVER_PRESENT_ATTR_ID(109),
    TRANSCEIVER_PRESENT_ATTR_ID(110),
    TRANSCEIVER_PRESENT_ATTR_ID(111),
    TRANSCEIVER_PRESENT_ATTR_ID(112),
    TRANSCEIVER_PRESENT_ATTR_ID(113),
    TRANSCEIVER_PRESENT_ATTR_ID(114),
    TRANSCEIVER_PRESENT_ATTR_ID(115),
    TRANSCEIVER_PRESENT_ATTR_ID(116),
    TRANSCEIVER_PRESENT_ATTR_ID(117),
    TRANSCEIVER_PRESENT_ATTR_ID(118),
    TRANSCEIVER_PRESENT_ATTR_ID(119),
    TRANSCEIVER_PRESENT_ATTR_ID(120),
    TRANSCEIVER_PRESENT_ATTR_ID(121),
    TRANSCEIVER_PRESENT_ATTR_ID(122),
    TRANSCEIVER_PRESENT_ATTR_ID(123),
    TRANSCEIVER_PRESENT_ATTR_ID(124),
    TRANSCEIVER_PRESENT_ATTR_ID(125),
    TRANSCEIVER_PRESENT_ATTR_ID(126),
    TRANSCEIVER_PRESENT_ATTR_ID(127),
    TRANSCEIVER_PRESENT_ATTR_ID(128),
    TRANSCEIVER_PRESENT_ATTR_ID(129),
    TRANSCEIVER_PRESENT_ATTR_ID(130),
    /*Reset*/
    TRANSCEIVER_RESET_ATTR_ID(1),
    TRANSCEIVER_RESET_ATTR_ID(2),
    TRANSCEIVER_RESET_ATTR_ID(3),
    TRANSCEIVER_RESET_ATTR_ID(4),
    TRANSCEIVER_RESET_ATTR_ID(5),
    TRANSCEIVER_RESET_ATTR_ID(6),
    TRANSCEIVER_RESET_ATTR_ID(7),
    TRANSCEIVER_RESET_ATTR_ID(8),
    TRANSCEIVER_RESET_ATTR_ID(9),
    TRANSCEIVER_RESET_ATTR_ID(10),
    TRANSCEIVER_RESET_ATTR_ID(11),
    TRANSCEIVER_RESET_ATTR_ID(12),
    TRANSCEIVER_RESET_ATTR_ID(13),
    TRANSCEIVER_RESET_ATTR_ID(14),
    TRANSCEIVER_RESET_ATTR_ID(15),
    TRANSCEIVER_RESET_ATTR_ID(16),
    TRANSCEIVER_RESET_ATTR_ID(17),
    TRANSCEIVER_RESET_ATTR_ID(18),
    TRANSCEIVER_RESET_ATTR_ID(19),
    TRANSCEIVER_RESET_ATTR_ID(20),
    TRANSCEIVER_RESET_ATTR_ID(21),
    TRANSCEIVER_RESET_ATTR_ID(22),
    TRANSCEIVER_RESET_ATTR_ID(23),
    TRANSCEIVER_RESET_ATTR_ID(24),
    TRANSCEIVER_RESET_ATTR_ID(25),
    TRANSCEIVER_RESET_ATTR_ID(26),
    TRANSCEIVER_RESET_ATTR_ID(27),
    TRANSCEIVER_RESET_ATTR_ID(28),
    TRANSCEIVER_RESET_ATTR_ID(29),
    TRANSCEIVER_RESET_ATTR_ID(30),
    TRANSCEIVER_RESET_ATTR_ID(31),
    TRANSCEIVER_RESET_ATTR_ID(32),
    TRANSCEIVER_RESET_ATTR_ID(33),
    TRANSCEIVER_RESET_ATTR_ID(34),
    TRANSCEIVER_RESET_ATTR_ID(35),
    TRANSCEIVER_RESET_ATTR_ID(36),
    TRANSCEIVER_RESET_ATTR_ID(37),
    TRANSCEIVER_RESET_ATTR_ID(38),
    TRANSCEIVER_RESET_ATTR_ID(39),
    TRANSCEIVER_RESET_ATTR_ID(40),
    TRANSCEIVER_RESET_ATTR_ID(41),
    TRANSCEIVER_RESET_ATTR_ID(42),
    TRANSCEIVER_RESET_ATTR_ID(43),
    TRANSCEIVER_RESET_ATTR_ID(44),
    TRANSCEIVER_RESET_ATTR_ID(45),
    TRANSCEIVER_RESET_ATTR_ID(46),
    TRANSCEIVER_RESET_ATTR_ID(47),
    TRANSCEIVER_RESET_ATTR_ID(48),
    TRANSCEIVER_RESET_ATTR_ID(49),
    TRANSCEIVER_RESET_ATTR_ID(50),
    TRANSCEIVER_RESET_ATTR_ID(51),
    TRANSCEIVER_RESET_ATTR_ID(52),
    TRANSCEIVER_RESET_ATTR_ID(53),
    TRANSCEIVER_RESET_ATTR_ID(54),
    TRANSCEIVER_RESET_ATTR_ID(55),
    TRANSCEIVER_RESET_ATTR_ID(56),
    TRANSCEIVER_RESET_ATTR_ID(57),
    TRANSCEIVER_RESET_ATTR_ID(58),
    TRANSCEIVER_RESET_ATTR_ID(59),
    TRANSCEIVER_RESET_ATTR_ID(60),
    TRANSCEIVER_RESET_ATTR_ID(61),
    TRANSCEIVER_RESET_ATTR_ID(62),
    TRANSCEIVER_RESET_ATTR_ID(63),
    TRANSCEIVER_RESET_ATTR_ID(64),
    TRANSCEIVER_RESET_ATTR_ID(65),
    TRANSCEIVER_RESET_ATTR_ID(66),
    TRANSCEIVER_RESET_ATTR_ID(67),
    TRANSCEIVER_RESET_ATTR_ID(68),
    TRANSCEIVER_RESET_ATTR_ID(69),
    TRANSCEIVER_RESET_ATTR_ID(70),
    TRANSCEIVER_RESET_ATTR_ID(71),
    TRANSCEIVER_RESET_ATTR_ID(72),
    TRANSCEIVER_RESET_ATTR_ID(73),
    TRANSCEIVER_RESET_ATTR_ID(74),
    TRANSCEIVER_RESET_ATTR_ID(75),
    TRANSCEIVER_RESET_ATTR_ID(76),
    TRANSCEIVER_RESET_ATTR_ID(77),
    TRANSCEIVER_RESET_ATTR_ID(78),
    TRANSCEIVER_RESET_ATTR_ID(79),
    TRANSCEIVER_RESET_ATTR_ID(80),
    TRANSCEIVER_RESET_ATTR_ID(81),
    TRANSCEIVER_RESET_ATTR_ID(82),
    TRANSCEIVER_RESET_ATTR_ID(83),
    TRANSCEIVER_RESET_ATTR_ID(84),
    TRANSCEIVER_RESET_ATTR_ID(85),
    TRANSCEIVER_RESET_ATTR_ID(86),
    TRANSCEIVER_RESET_ATTR_ID(87),
    TRANSCEIVER_RESET_ATTR_ID(88),
    TRANSCEIVER_RESET_ATTR_ID(89),
    TRANSCEIVER_RESET_ATTR_ID(90),
    TRANSCEIVER_RESET_ATTR_ID(91),
    TRANSCEIVER_RESET_ATTR_ID(92),
    TRANSCEIVER_RESET_ATTR_ID(93),
    TRANSCEIVER_RESET_ATTR_ID(94),
    TRANSCEIVER_RESET_ATTR_ID(95),
    TRANSCEIVER_RESET_ATTR_ID(96),
    TRANSCEIVER_RESET_ATTR_ID(97),
    TRANSCEIVER_RESET_ATTR_ID(98),
    TRANSCEIVER_RESET_ATTR_ID(99),
    TRANSCEIVER_RESET_ATTR_ID(100),
    TRANSCEIVER_RESET_ATTR_ID(101),
    TRANSCEIVER_RESET_ATTR_ID(102),
    TRANSCEIVER_RESET_ATTR_ID(103),
    TRANSCEIVER_RESET_ATTR_ID(104),
    TRANSCEIVER_RESET_ATTR_ID(105),
    TRANSCEIVER_RESET_ATTR_ID(106),
    TRANSCEIVER_RESET_ATTR_ID(107),
    TRANSCEIVER_RESET_ATTR_ID(108),
    TRANSCEIVER_RESET_ATTR_ID(109),
    TRANSCEIVER_RESET_ATTR_ID(110),
    TRANSCEIVER_RESET_ATTR_ID(111),
    TRANSCEIVER_RESET_ATTR_ID(112),
    TRANSCEIVER_RESET_ATTR_ID(113),
    TRANSCEIVER_RESET_ATTR_ID(114),
    TRANSCEIVER_RESET_ATTR_ID(115),
    TRANSCEIVER_RESET_ATTR_ID(116),
    TRANSCEIVER_RESET_ATTR_ID(117),
    TRANSCEIVER_RESET_ATTR_ID(118),
    TRANSCEIVER_RESET_ATTR_ID(119),
    TRANSCEIVER_RESET_ATTR_ID(120),
    TRANSCEIVER_RESET_ATTR_ID(121),
    TRANSCEIVER_RESET_ATTR_ID(122),
    TRANSCEIVER_RESET_ATTR_ID(123),
    TRANSCEIVER_RESET_ATTR_ID(124),
    TRANSCEIVER_RESET_ATTR_ID(125),
    TRANSCEIVER_RESET_ATTR_ID(126),
    TRANSCEIVER_RESET_ATTR_ID(127),
    TRANSCEIVER_RESET_ATTR_ID(128),
    TRANSCEIVER_LPMODE_ATTR_ID(1),
    TRANSCEIVER_LPMODE_ATTR_ID(2),
    TRANSCEIVER_LPMODE_ATTR_ID(3),
    TRANSCEIVER_LPMODE_ATTR_ID(4),
    TRANSCEIVER_LPMODE_ATTR_ID(5),
    TRANSCEIVER_LPMODE_ATTR_ID(6),
    TRANSCEIVER_LPMODE_ATTR_ID(7),
    TRANSCEIVER_LPMODE_ATTR_ID(8),
    TRANSCEIVER_LPMODE_ATTR_ID(9),
    TRANSCEIVER_LPMODE_ATTR_ID(10),
    TRANSCEIVER_LPMODE_ATTR_ID(11),
    TRANSCEIVER_LPMODE_ATTR_ID(12),
    TRANSCEIVER_LPMODE_ATTR_ID(13),
    TRANSCEIVER_LPMODE_ATTR_ID(14),
    TRANSCEIVER_LPMODE_ATTR_ID(15),
    TRANSCEIVER_LPMODE_ATTR_ID(16),
    TRANSCEIVER_LPMODE_ATTR_ID(17),
    TRANSCEIVER_LPMODE_ATTR_ID(18),
    TRANSCEIVER_LPMODE_ATTR_ID(19),
    TRANSCEIVER_LPMODE_ATTR_ID(20),
    TRANSCEIVER_LPMODE_ATTR_ID(21),
    TRANSCEIVER_LPMODE_ATTR_ID(22),
    TRANSCEIVER_LPMODE_ATTR_ID(23),
    TRANSCEIVER_LPMODE_ATTR_ID(24),
    TRANSCEIVER_LPMODE_ATTR_ID(25),
    TRANSCEIVER_LPMODE_ATTR_ID(26),
    TRANSCEIVER_LPMODE_ATTR_ID(27),
    TRANSCEIVER_LPMODE_ATTR_ID(28),
    TRANSCEIVER_LPMODE_ATTR_ID(29),
    TRANSCEIVER_LPMODE_ATTR_ID(30),
    TRANSCEIVER_LPMODE_ATTR_ID(31),
    TRANSCEIVER_LPMODE_ATTR_ID(32),
    TRANSCEIVER_LPMODE_ATTR_ID(33),
    TRANSCEIVER_LPMODE_ATTR_ID(34),
    TRANSCEIVER_LPMODE_ATTR_ID(35),
    TRANSCEIVER_LPMODE_ATTR_ID(36),
    TRANSCEIVER_LPMODE_ATTR_ID(37),
    TRANSCEIVER_LPMODE_ATTR_ID(38),
    TRANSCEIVER_LPMODE_ATTR_ID(39),
    TRANSCEIVER_LPMODE_ATTR_ID(40),
    TRANSCEIVER_LPMODE_ATTR_ID(41),
    TRANSCEIVER_LPMODE_ATTR_ID(42),
    TRANSCEIVER_LPMODE_ATTR_ID(43),
    TRANSCEIVER_LPMODE_ATTR_ID(44),
    TRANSCEIVER_LPMODE_ATTR_ID(45),
    TRANSCEIVER_LPMODE_ATTR_ID(46),
    TRANSCEIVER_LPMODE_ATTR_ID(47),
    TRANSCEIVER_LPMODE_ATTR_ID(48),
    TRANSCEIVER_LPMODE_ATTR_ID(49),
    TRANSCEIVER_LPMODE_ATTR_ID(50),
    TRANSCEIVER_LPMODE_ATTR_ID(51),
    TRANSCEIVER_LPMODE_ATTR_ID(52),
    TRANSCEIVER_LPMODE_ATTR_ID(53),
    TRANSCEIVER_LPMODE_ATTR_ID(54),
    TRANSCEIVER_LPMODE_ATTR_ID(55),
    TRANSCEIVER_LPMODE_ATTR_ID(56),
    TRANSCEIVER_LPMODE_ATTR_ID(57),
    TRANSCEIVER_LPMODE_ATTR_ID(58),
    TRANSCEIVER_LPMODE_ATTR_ID(59),
    TRANSCEIVER_LPMODE_ATTR_ID(60),
    TRANSCEIVER_LPMODE_ATTR_ID(61),
    TRANSCEIVER_LPMODE_ATTR_ID(62),
    TRANSCEIVER_LPMODE_ATTR_ID(63),
    TRANSCEIVER_LPMODE_ATTR_ID(64),
    TRANSCEIVER_LPMODE_ATTR_ID(65),
    TRANSCEIVER_LPMODE_ATTR_ID(66),
    TRANSCEIVER_LPMODE_ATTR_ID(67),
    TRANSCEIVER_LPMODE_ATTR_ID(68),
    TRANSCEIVER_LPMODE_ATTR_ID(69),
    TRANSCEIVER_LPMODE_ATTR_ID(70),
    TRANSCEIVER_LPMODE_ATTR_ID(71),
    TRANSCEIVER_LPMODE_ATTR_ID(72),
    TRANSCEIVER_LPMODE_ATTR_ID(73),
    TRANSCEIVER_LPMODE_ATTR_ID(74),
    TRANSCEIVER_LPMODE_ATTR_ID(75),
    TRANSCEIVER_LPMODE_ATTR_ID(76),
    TRANSCEIVER_LPMODE_ATTR_ID(77),
    TRANSCEIVER_LPMODE_ATTR_ID(78),
    TRANSCEIVER_LPMODE_ATTR_ID(79),
    TRANSCEIVER_LPMODE_ATTR_ID(80),
    TRANSCEIVER_LPMODE_ATTR_ID(81),
    TRANSCEIVER_LPMODE_ATTR_ID(82),
    TRANSCEIVER_LPMODE_ATTR_ID(83),
    TRANSCEIVER_LPMODE_ATTR_ID(84),
    TRANSCEIVER_LPMODE_ATTR_ID(85),
    TRANSCEIVER_LPMODE_ATTR_ID(86),
    TRANSCEIVER_LPMODE_ATTR_ID(87),
    TRANSCEIVER_LPMODE_ATTR_ID(88),
    TRANSCEIVER_LPMODE_ATTR_ID(89),
    TRANSCEIVER_LPMODE_ATTR_ID(90),
    TRANSCEIVER_LPMODE_ATTR_ID(91),
    TRANSCEIVER_LPMODE_ATTR_ID(92),
    TRANSCEIVER_LPMODE_ATTR_ID(93),
    TRANSCEIVER_LPMODE_ATTR_ID(94),
    TRANSCEIVER_LPMODE_ATTR_ID(95),
    TRANSCEIVER_LPMODE_ATTR_ID(96),
    TRANSCEIVER_LPMODE_ATTR_ID(97),
    TRANSCEIVER_LPMODE_ATTR_ID(98),
    TRANSCEIVER_LPMODE_ATTR_ID(99),
    TRANSCEIVER_LPMODE_ATTR_ID(100),
    TRANSCEIVER_LPMODE_ATTR_ID(101),
    TRANSCEIVER_LPMODE_ATTR_ID(102),
    TRANSCEIVER_LPMODE_ATTR_ID(103),
    TRANSCEIVER_LPMODE_ATTR_ID(104),
    TRANSCEIVER_LPMODE_ATTR_ID(105),
    TRANSCEIVER_LPMODE_ATTR_ID(106),
    TRANSCEIVER_LPMODE_ATTR_ID(107),
    TRANSCEIVER_LPMODE_ATTR_ID(108),
    TRANSCEIVER_LPMODE_ATTR_ID(109),
    TRANSCEIVER_LPMODE_ATTR_ID(110),
    TRANSCEIVER_LPMODE_ATTR_ID(111),
    TRANSCEIVER_LPMODE_ATTR_ID(112),
    TRANSCEIVER_LPMODE_ATTR_ID(113),
    TRANSCEIVER_LPMODE_ATTR_ID(114),
    TRANSCEIVER_LPMODE_ATTR_ID(115),
    TRANSCEIVER_LPMODE_ATTR_ID(116),
    TRANSCEIVER_LPMODE_ATTR_ID(117),
    TRANSCEIVER_LPMODE_ATTR_ID(118),
    TRANSCEIVER_LPMODE_ATTR_ID(119),
    TRANSCEIVER_LPMODE_ATTR_ID(120),
    TRANSCEIVER_LPMODE_ATTR_ID(121),
    TRANSCEIVER_LPMODE_ATTR_ID(122),
    TRANSCEIVER_LPMODE_ATTR_ID(123),
    TRANSCEIVER_LPMODE_ATTR_ID(124),
    TRANSCEIVER_LPMODE_ATTR_ID(125),
    TRANSCEIVER_LPMODE_ATTR_ID(126),
    TRANSCEIVER_LPMODE_ATTR_ID(127),
    TRANSCEIVER_LPMODE_ATTR_ID(128),
    TRANSCEIVER_TX_DISABLE_ATTR_ID(129),
    TRANSCEIVER_TX_DISABLE_ATTR_ID(130),
    TRANSCEIVER_TX_FAULT_ATTR_ID(129),
    TRANSCEIVER_TX_FAULT_ATTR_ID(130),
    TRANSCEIVER_RX_LOS_ATTR_ID(129),
    TRANSCEIVER_RX_LOS_ATTR_ID(130),
};

/***********************************************
 *       function declare
 * *********************************************/
static ssize_t status_read(struct device *dev, struct device_attribute *da,
             char *buf);
static ssize_t status_write(struct device *dev, struct device_attribute *da,
            const char *buf, size_t count);

#define DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(index) \
    static SENSOR_DEVICE_ATTR(module_present_##index, S_IRUGO, status_read, NULL, MODULE_PRESENT_##index); \
    static SENSOR_DEVICE_ATTR(module_reset_##index, S_IRUGO|S_IWUSR, status_read, status_write, MODULE_RESET_##index); \
    static SENSOR_DEVICE_ATTR(module_lp_mode_##index, S_IRUGO|S_IWUSR, status_read, status_write, MODULE_LPMODE_##index)
#define DECLARE_TRANSCEIVER_ATTR(index) \
    &sensor_dev_attr_module_present_##index.dev_attr.attr, \
    &sensor_dev_attr_module_reset_##index.dev_attr.attr, \
    &sensor_dev_attr_module_lp_mode_##index.dev_attr.attr

/* transceiver attributes */
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(1);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(2);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(3);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(4);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(5);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(6);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(7);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(8);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(9);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(10);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(11);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(12);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(13);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(14);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(15);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(16);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(17);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(18);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(19);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(20);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(21);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(22);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(23);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(24);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(25);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(26);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(27);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(28);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(29);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(30);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(31);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(32);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(33);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(34);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(35);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(36);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(37);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(38);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(39);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(40);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(41);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(42);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(43);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(44);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(45);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(46);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(47);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(48);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(49);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(50);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(51);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(52);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(53);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(54);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(55);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(56);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(57);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(58);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(59);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(60);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(61);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(62);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(63);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(64);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(65);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(66);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(67);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(68);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(69);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(70);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(71);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(72);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(73),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(74),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(75),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(76),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(77),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(78),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(79),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(80),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(81),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(82),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(83),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(84),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(85),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(86),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(87),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(88),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(89),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(90),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(91),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(92),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(93),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(94),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(95),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(96),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(97),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(98),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(99),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(100),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(101),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(102),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(103),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(104),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(105),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(106),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(107),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(108),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(109),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(110),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(111),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(112),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(113),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(114),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(115),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(116),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(117),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(118),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(119),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(120),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(121),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(122),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(123),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(124),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(125),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(126),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(127),
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(128),
static SENSOR_DEVICE_ATTR(module_present_129, S_IRUGO, status_read, NULL, MODULE_PRESENT_129);
static SENSOR_DEVICE_ATTR(module_present_130, S_IRUGO, status_read, NULL, MODULE_PRESENT_130);
static SENSOR_DEVICE_ATTR(module_tx_disable_129, S_IRUGO|S_IWUSR, status_read,
                          status_write, MODULE_TX_DISABLE_129);
static SENSOR_DEVICE_ATTR(module_tx_disable_130, S_IRUGO|S_IWUSR, status_read,
                          status_write, MODULE_TX_DISABLE_130);
static SENSOR_DEVICE_ATTR(module_tx_fault_129, S_IRUGO, status_read, NULL, MODULE_TX_FAULT_129);
static SENSOR_DEVICE_ATTR(module_tx_fault_130, S_IRUGO, status_read, NULL, MODULE_TX_FAULT_130);
static SENSOR_DEVICE_ATTR(module_rx_los_129, S_IRUGO, status_read, NULL, MODULE_RX_LOS_129);
static SENSOR_DEVICE_ATTR(MODULE_RX_LOS_130, S_IRUGO, status_read, NULL, MODULE_RX_LOS_130);

static struct attribute *fpga_transceiver_attributes[] = {
    DECLARE_TRANSCEIVER_ATTR(1),
    DECLARE_TRANSCEIVER_ATTR(2),
    DECLARE_TRANSCEIVER_ATTR(3),
    DECLARE_TRANSCEIVER_ATTR(4),
    DECLARE_TRANSCEIVER_ATTR(5),
    DECLARE_TRANSCEIVER_ATTR(6),
    DECLARE_TRANSCEIVER_ATTR(7),
    DECLARE_TRANSCEIVER_ATTR(8),
    DECLARE_TRANSCEIVER_ATTR(9),
    DECLARE_TRANSCEIVER_ATTR(10),
    DECLARE_TRANSCEIVER_ATTR(11),
    DECLARE_TRANSCEIVER_ATTR(12),
    DECLARE_TRANSCEIVER_ATTR(13),
    DECLARE_TRANSCEIVER_ATTR(14),
    DECLARE_TRANSCEIVER_ATTR(15),
    DECLARE_TRANSCEIVER_ATTR(16),
    DECLARE_TRANSCEIVER_ATTR(17),
    DECLARE_TRANSCEIVER_ATTR(18),
    DECLARE_TRANSCEIVER_ATTR(19),
    DECLARE_TRANSCEIVER_ATTR(20),
    DECLARE_TRANSCEIVER_ATTR(21),
    DECLARE_TRANSCEIVER_ATTR(22),
    DECLARE_TRANSCEIVER_ATTR(23),
    DECLARE_TRANSCEIVER_ATTR(24),
    DECLARE_TRANSCEIVER_ATTR(25),
    DECLARE_TRANSCEIVER_ATTR(26),
    DECLARE_TRANSCEIVER_ATTR(27),
    DECLARE_TRANSCEIVER_ATTR(28),
    DECLARE_TRANSCEIVER_ATTR(29),
    DECLARE_TRANSCEIVER_ATTR(30),
    DECLARE_TRANSCEIVER_ATTR(31),
    DECLARE_TRANSCEIVER_ATTR(32),
    DECLARE_TRANSCEIVER_ATTR(33),
    DECLARE_TRANSCEIVER_ATTR(34),
    DECLARE_TRANSCEIVER_ATTR(35),
    DECLARE_TRANSCEIVER_ATTR(36),
    DECLARE_TRANSCEIVER_ATTR(37),
    DECLARE_TRANSCEIVER_ATTR(38),
    DECLARE_TRANSCEIVER_ATTR(39),
    DECLARE_TRANSCEIVER_ATTR(40),
    DECLARE_TRANSCEIVER_ATTR(41),
    DECLARE_TRANSCEIVER_ATTR(42),
    DECLARE_TRANSCEIVER_ATTR(43),
    DECLARE_TRANSCEIVER_ATTR(44),
    DECLARE_TRANSCEIVER_ATTR(45),
    DECLARE_TRANSCEIVER_ATTR(46),
    DECLARE_TRANSCEIVER_ATTR(47),
    DECLARE_TRANSCEIVER_ATTR(48),
    DECLARE_TRANSCEIVER_ATTR(49),
    DECLARE_TRANSCEIVER_ATTR(50),
    DECLARE_TRANSCEIVER_ATTR(51),
    DECLARE_TRANSCEIVER_ATTR(52),
    DECLARE_TRANSCEIVER_ATTR(53),
    DECLARE_TRANSCEIVER_ATTR(54),
    DECLARE_TRANSCEIVER_ATTR(55),
    DECLARE_TRANSCEIVER_ATTR(56),
    DECLARE_TRANSCEIVER_ATTR(57),
    DECLARE_TRANSCEIVER_ATTR(58),
    DECLARE_TRANSCEIVER_ATTR(59),
    DECLARE_TRANSCEIVER_ATTR(60),
    DECLARE_TRANSCEIVER_ATTR(61),
    DECLARE_TRANSCEIVER_ATTR(62),
    DECLARE_TRANSCEIVER_ATTR(63),
    DECLARE_TRANSCEIVER_ATTR(64),
    DECLARE_TRANSCEIVER_ATTR(65),
    DECLARE_TRANSCEIVER_ATTR(66),
    DECLARE_TRANSCEIVER_ATTR(67),
    DECLARE_TRANSCEIVER_ATTR(68),
    DECLARE_TRANSCEIVER_ATTR(69),
    DECLARE_TRANSCEIVER_ATTR(70),
    DECLARE_TRANSCEIVER_ATTR(71),
    DECLARE_TRANSCEIVER_ATTR(72),
    DECLARE_TRANSCEIVER_ATTR(73),
    DECLARE_TRANSCEIVER_ATTR(74),
    DECLARE_TRANSCEIVER_ATTR(75),
    DECLARE_TRANSCEIVER_ATTR(76),
    DECLARE_TRANSCEIVER_ATTR(77),
    DECLARE_TRANSCEIVER_ATTR(78),
    DECLARE_TRANSCEIVER_ATTR(79),
    DECLARE_TRANSCEIVER_ATTR(80),
    DECLARE_TRANSCEIVER_ATTR(81),
    DECLARE_TRANSCEIVER_ATTR(82),
    DECLARE_TRANSCEIVER_ATTR(83),
    DECLARE_TRANSCEIVER_ATTR(84),
    DECLARE_TRANSCEIVER_ATTR(85),
    DECLARE_TRANSCEIVER_ATTR(86),
    DECLARE_TRANSCEIVER_ATTR(87),
    DECLARE_TRANSCEIVER_ATTR(88),
    DECLARE_TRANSCEIVER_ATTR(89),
    DECLARE_TRANSCEIVER_ATTR(90),
    DECLARE_TRANSCEIVER_ATTR(91),
    DECLARE_TRANSCEIVER_ATTR(92),
    DECLARE_TRANSCEIVER_ATTR(93),
    DECLARE_TRANSCEIVER_ATTR(94),
    DECLARE_TRANSCEIVER_ATTR(95),
    DECLARE_TRANSCEIVER_ATTR(96),
    DECLARE_TRANSCEIVER_ATTR(97),
    DECLARE_TRANSCEIVER_ATTR(98),
    DECLARE_TRANSCEIVER_ATTR(99),
    DECLARE_TRANSCEIVER_ATTR(100),
    DECLARE_TRANSCEIVER_ATTR(101),
    DECLARE_TRANSCEIVER_ATTR(102),
    DECLARE_TRANSCEIVER_ATTR(103),
    DECLARE_TRANSCEIVER_ATTR(104),
    DECLARE_TRANSCEIVER_ATTR(105),
    DECLARE_TRANSCEIVER_ATTR(106),
    DECLARE_TRANSCEIVER_ATTR(107),
    DECLARE_TRANSCEIVER_ATTR(108),
    DECLARE_TRANSCEIVER_ATTR(109),
    DECLARE_TRANSCEIVER_ATTR(110),
    DECLARE_TRANSCEIVER_ATTR(111),
    DECLARE_TRANSCEIVER_ATTR(112),
    DECLARE_TRANSCEIVER_ATTR(113),
    DECLARE_TRANSCEIVER_ATTR(114),
    DECLARE_TRANSCEIVER_ATTR(115),
    DECLARE_TRANSCEIVER_ATTR(116),
    DECLARE_TRANSCEIVER_ATTR(117),
    DECLARE_TRANSCEIVER_ATTR(118),
    DECLARE_TRANSCEIVER_ATTR(119),
    DECLARE_TRANSCEIVER_ATTR(120),
    DECLARE_TRANSCEIVER_ATTR(121),
    DECLARE_TRANSCEIVER_ATTR(122),
    DECLARE_TRANSCEIVER_ATTR(123),
    DECLARE_TRANSCEIVER_ATTR(124),
    DECLARE_TRANSCEIVER_ATTR(125),
    DECLARE_TRANSCEIVER_ATTR(126),
    DECLARE_TRANSCEIVER_ATTR(127),
    DECLARE_TRANSCEIVER_ATTR(128),
    &sensor_dev_attr_module_present_129.dev_attr.attr,
    &sensor_dev_attr_module_present_130.dev_attr.attr,
    &sensor_dev_attr_module_tx_disable_129.dev_attr.attr,
    &sensor_dev_attr_module_tx_disable_130.dev_attr.attr,
    &sensor_dev_attr_module_tx_fault_129.dev_attr.attr,
    &sensor_dev_attr_module_tx_fault_130.dev_attr.attr,
    &sensor_dev_attr_module_rx_los_129.dev_attr.attr,
    &sensor_dev_attr_module_rx_los_130.dev_attr.attr,
    NULL
};

static const struct attribute_group fpga_port_stat_group = {
    .attrs = fpga_transceiver_attributes,
};

struct attribute_mapping {
    u16 attr_base;
    u16 reg;
    u8 revert;
};

// Define an array of attribute mappings
static struct attribute_mapping attribute_mappings[] = {
    [MODULE_PRESENT_1 ... MODULE_PRESENT_8]   = {MODULE_PRESENT_1,  XCVR_P8_P1_RESET_REG, 1},
    [MODULE_PRESENT_9 ... MODULE_PRESENT_16]  = {MODULE_PRESENT_9,  XCVR_P16_P9_RESET_REG, 1},
    [MODULE_PRESENT_17 ... MODULE_PRESENT_24] = {MODULE_PRESENT_17, XCVR_P24_P17_RESET_REG, 1},
    [MODULE_PRESENT_25 ... MODULE_PRESENT_32] = {MODULE_PRESENT_25, XCVR_P32_P25_RESET_REG, 1},

    [MODULE_PRESENT_33 ... MODULE_PRESENT_36] = {MODULE_PRESENT_33, XCVR_P36_P33_RESET_REG, 1},
    [MODULE_PRESENT_37 ... MODULE_PRESENT_40] = {MODULE_PRESENT_37, XCVR_P40_P37_RESET_REG, 1},
    [MODULE_PRESENT_41 ... MODULE_PRESENT_44] = {MODULE_PRESENT_41, XCVR_P44_P41_RESET_REG, 1},
    [MODULE_PRESENT_45 ... MODULE_PRESENT_48] = {MODULE_PRESENT_45, XCVR_P48_P45_RESET_REG, 1},

    [MODULE_PRESENT_49 ... MODULE_PRESENT_52] = {MODULE_PRESENT_49, XCVR_P52_P49_RESET_REG, 1},
    [MODULE_PRESENT_53 ... MODULE_PRESENT_56] = {MODULE_PRESENT_53, XCVR_P56_P53_RESET_REG, 1},
    [MODULE_PRESENT_57 ... MODULE_PRESENT_60] = {MODULE_PRESENT_57, XCVR_P60_P57_RESET_REG, 1},
    [MODULE_PRESENT_61 ... MODULE_PRESENT_64] = {MODULE_PRESENT_61, XCVR_P64_P61_RESET_REG, 1},

    [MODULE_PRESENT_65 ... MODULE_PRESENT_68] = {MODULE_PRESENT_65, XCVR_P68_P65_RESET_REG, 1},
    [MODULE_PRESENT_69 ... MODULE_PRESENT_72] = {MODULE_PRESENT_69, XCVR_P72_P69_RESET_REG, 1},
    [MODULE_PRESENT_73 ... MODULE_PRESENT_76] = {MODULE_PRESENT_73, XCVR_P76_P73_RESET_REG, 1},
    [MODULE_PRESENT_77 ... MODULE_PRESENT_80] = {MODULE_PRESENT_77, XCVR_P80_P77_RESET_REG, 1},

    [MODULE_PRESENT_81 ... MODULE_PRESENT_84] = {MODULE_PRESENT_81, XCVR_P84_P81_RESET_REG, 1},
    [MODULE_PRESENT_85 ... MODULE_PRESENT_88] = {MODULE_PRESENT_85, XCVR_P88_P85_RESET_REG, 1},
    [MODULE_PRESENT_89 ... MODULE_PRESENT_92] = {MODULE_PRESENT_89, XCVR_P92_P89_RESET_REG, 1},
    [MODULE_PRESENT_93 ... MODULE_PRESENT_96] = {MODULE_PRESENT_93, XCVR_P96_P93_RESET_REG, 1},

    [MODULE_PRESENT_97 ... MODULE_PRESENT_104]  = {MODULE_PRESENT_97,  XCVR_P104_P97_RESET_REG, 1},
    [MODULE_PRESENT_105 ... MODULE_PRESENT_112] = {MODULE_PRESENT_105, XCVR_P112_P105_RESET_REG, 1},

    [MODULE_PRESENT_113 ... MODULE_PRESENT_120] = {MODULE_PRESENT_113, XCVR_P120_P113_RESET_REG, 1},
    [MODULE_PRESENT_121 ... MODULE_PRESENT_128] = {MODULE_PRESENT_121, XCVR_P128_P121_RESET_REG, 1},
    /* SFP */
    [MODULE_PRESENT_129 ... MODULE_PRESENT_130] = {MODULE_PRESENT_129, XCVR_P130_P129_PRESENT_REG, 1},

    [MODULE_LPMODE_1 ... MODULE_LPMODE_8]     = {MODULE_LPMODE_1,  XCVR_P8_P1_LPMODE_REG, 1},
    [MODULE_LPMODE_9 ... MODULE_LPMODE_16]    = {MODULE_LPMODE_9,  XCVR_P16_P9_LPMODE_REG, 1},
    [MODULE_LPMODE_17 ... MODULE_LPMODE_24]   = {MODULE_LPMODE_17, XCVR_P24_P17_LPMODE_REG, 1},
    [MODULE_LPMODE_25 ... MODULE_LPMODE_32]   = {MODULE_LPMODE_25, XCVR_P32_P25_LPMODE_REG, 1},

    [MODULE_LPMODE_33 ... MODULE_LPMODE_36]   = {MODULE_LPMODE_33, XCVR_P36_P33_LPMODE_REG, 1},
    [MODULE_LPMODE_37 ... MODULE_LPMODE_40]   = {MODULE_LPMODE_37, XCVR_P40_P37_LPMODE_REG, 1},
    [MODULE_LPMODE_41 ... MODULE_LPMODE_44]   = {MODULE_LPMODE_41, XCVR_P44_P41_LPMODE_REG, 1},
    [MODULE_LPMODE_45 ... MODULE_LPMODE_48]   = {MODULE_LPMODE_45, XCVR_P48_P45_LPMODE_REG, 1},

    [MODULE_LPMODE_49 ... MODULE_LPMODE_52]   = {MODULE_LPMODE_49, XCVR_P52_P49_LPMODE_REG, 1},
    [MODULE_LPMODE_53 ... MODULE_LPMODE_56]   = {MODULE_LPMODE_53, XCVR_P56_P53_LPMODE_REG, 1},
    [MODULE_LPMODE_57 ... MODULE_LPMODE_60]   = {MODULE_LPMODE_57, XCVR_P60_P57_LPMODE_REG, 1},
    [MODULE_LPMODE_61 ... MODULE_LPMODE_64]   = {MODULE_LPMODE_61, XCVR_P64_P61_LPMODE_REG, 1},

    [MODULE_LPMODE_65 ... MODULE_LPMODE_68]   = {MODULE_LPMODE_65, XCVR_P68_P65_LPMODE_REG, 1},
    [MODULE_LPMODE_69 ... MODULE_LPMODE_72]   = {MODULE_LPMODE_69, XCVR_P72_P69_LPMODE_REG, 1},
    [MODULE_LPMODE_73 ... MODULE_LPMODE_76]   = {MODULE_LPMODE_73, XCVR_P76_P73_LPMODE_REG, 1},
    [MODULE_LPMODE_77 ... MODULE_LPMODE_80]   = {MODULE_LPMODE_77, XCVR_P80_P77_LPMODE_REG, 1},

    [MODULE_LPMODE_81 ... MODULE_LPMODE_84]   = {MODULE_LPMODE_81, XCVR_P84_P81_LPMODE_REG, 1},
    [MODULE_LPMODE_85 ... MODULE_LPMODE_88]   = {MODULE_LPMODE_85, XCVR_P88_P85_LPMODE_REG, 1},
    [MODULE_LPMODE_89 ... MODULE_LPMODE_92]   = {MODULE_LPMODE_89, XCVR_P92_P89_LPMODE_REG, 1},
    [MODULE_LPMODE_93 ... MODULE_LPMODE_96]   = {MODULE_LPMODE_93, XCVR_P96_P93_LPMODE_REG, 1},

    [MODULE_LPMODE_97 ... MODULE_LPMODE_104]  = {MODULE_LPMODE_97,  XCVR_P104_P97_LPMODE_REG, 1},
    [MODULE_LPMODE_105 ... MODULE_LPMODE_112] = {MODULE_LPMODE_105, XCVR_P112_P105_LPMODE_REG, 1},

    [MODULE_LPMODE_113 ... MODULE_LPMODE_120] = {MODULE_LPMODE_113, XCVR_P120_P113_LPMODE_REG, 1},
    [MODULE_LPMODE_121 ... MODULE_LPMODE_128] = {MODULE_LPMODE_121, XCVR_P128_P121_LPMODE_REG, 1},
    [MODULE_TX_DISABLE_129 ... MODULE_TX_DISABLE_130] ={MODULE_TX_DISABLE_129, XCVR_P130_P129_TXDIS_REG,  0},
    [MODULE_TX_FAULT_129 ... MODULE_TX_FAULT_130] = {MODULE_TX_FAULT_129, XCVR_P130_P129_TXFAULT_REG, 0},
    [MODULE_RX_LOS_129 ... MODULE_RX_LOS_130] = {MODULE_RX_LOS_129, XCVR_P130_P129_RXLOS_REG, 0},
};

static inline unsigned int fpga_read(const void __iomem *addr, u32 spi_mask)
{
    wait_spi(spi_mask, usecs_to_jiffies(20));
    return ioread8(addr);
}

static inline void fpga_write(void __iomem *addr, u8 val, u32 spi_mask)
{
    wait_spi(spi_mask, usecs_to_jiffies(20));
    iowrite8(val, addr);
}

static ssize_t status_read(struct device *dev, struct device_attribute *da, char *buf)
{
    struct sensor_device_attribute *attr = to_sensor_dev_attr(da);
    struct as1813_128_fpga_data *fpga_ctl = dev_get_drvdata(dev);
    ssize_t ret = -EINVAL;
    u16 reg;
    u8 fpga_spi_mux_data, reg_val;
    u8 bits_shift, port_index;

    switch(attr->index)
    {
        /* MEZZ TOP_L */
        case MODULE_PRESENT_1 ... MODULE_PRESENT_16:
        case MODULE_LPMODE_1 ... MODULE_LPMODE_16:
        case MODULE_RESET_1 ... MODULE_RESET_16:
            fpga_spi_mux_data = 0x04;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            bits_shift = port_index;
            break;

        /* MEZZ TOP_R */
        case MODULE_PRESENT_17 ... MODULE_PRESENT_32:
        case MODULE_LPMODE_17 ... MODULE_LPMODE_32:
        case MODULE_RESET_17 ... MODULE_RESET_32:
            fpga_spi_mux_data = 0x05;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            bits_shift = port_index;
            break;

        /* MB CPLD0 */
        case MODULE_PRESENT_33 ... MODULE_PRESENT_48:
        case MODULE_LPMODE_33 ... MODULE_LPMODE_48:
        case MODULE_RESET_33 ... MODULE_RESET_48:
            fpga_spi_mux_data = 0x00;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            if (port_index < 2)
                bits_shift = port_index;
            else
                bits_shift = port_index + 2;
            break;

        /* MB CPLD1 */
        case MODULE_PRESENT_49 ... MODULE_PRESENT_64:
        case MODULE_LPMODE_49 ... MODULE_LPMODE_64:
        case MODULE_RESET_49 ... MODULE_RESET_64:
            fpga_spi_mux_data = 0x01;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            if (port_index < 2)
                bits_shift = port_index;
            else
                bits_shift = port_index + 2;
            break;

        /* MB CPLD0 */
        case MODULE_PRESENT_65 ... MODULE_PRESENT_80:
        case MODULE_LPMODE_65 ... MODULE_LPMODE_80:
        case MODULE_RESET_65 ... MODULE_RESET_80:
            fpga_spi_mux_data = 0x00;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            if (port_index < 2)
                bits_shift = port_index + 2;
            else
                bits_shift = port_index + 4;
            break;

        /* MB CPLD1 */
        case MODULE_PRESENT_81 ... MODULE_PRESENT_96:
        case MODULE_LPMODE_81 ... MODULE_LPMODE_96:
        case MODULE_RESET_81 ... MODULE_RESET_96:
            fpga_spi_mux_data = 0x01;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            if (port_index < 2)
                bits_shift = port_index + 2;
            else
                bits_shift = port_index + 4;
            break;

        /* MEZZ BOT_L */
        case MODULE_PRESENT_97 ... MODULE_PRESENT_112:
        case MODULE_LPMODE_97 ... MODULE_LPMODE_112:
        case MODULE_RESET_97 ... MODULE_RESET_112:
            fpga_spi_mux_data = 0x02;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            bits_shift = port_index;
            break;

        /* MEZZ BOT_R */
        case MODULE_PRESENT_113 ... MODULE_PRESENT_128:
        case MODULE_LPMODE_113 ... MODULE_LPMODE_128:
        case MODULE_RESET_113 ... MODULE_RESET_128:
            fpga_spi_mux_data = 0x03;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            bits_shift = port_index;
            break;

        /* SFP 129-130 (MB CPLD1) */
        case MODULE_PRESENT_129 ... MODULE_PRESENT_130:
        case MODULE_TX_DISABLE_129 ... MODULE_TX_DISABLE_130:
        case MODULE_RX_LOS_129 ... MODULE_RX_LOS_130:
        case MODULE_TX_FAULT_129 ... MODULE_TX_FAULT_130:
            fpga_spi_mux_data = 0x01;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            bits_shift = port_index;
            break;

        default:
            break;
    }

    reg = attribute_mappings[attr->index].reg;

    LOCK(&cpld_access_lock);
    iowrite8(fpga_spi_mux_data, spi_mux_reg);
    reg_val = fpga_read(fpga_ctl->pci_fpga_dev.data_base_addr0 + reg, SPI_BUSY_MASK_CPLD);
    UNLOCK(&cpld_access_lock);
    reg_val = (reg_val >> bits_shift) & 0x01;

    if (attribute_mappings[attr->index].revert) 
        reg_val = !reg_val;
    ret = sprintf(buf, "%u\n", reg_val);

    return ret;
}

static ssize_t status_write(struct device *dev, struct device_attribute *da,
                            const char *buf, size_t count)
{
    struct sensor_device_attribute *attr = to_sensor_dev_attr(da);
    struct as1813_128_fpga_data *fpga_ctl = dev_get_drvdata(dev);
    void __iomem *addr;
    int status;
    u16 reg;
    u8 input, fpga_spi_mux_data;
    u8 reg_val, bit_mask, should_set_bit, port_index;
    u32 spi_mask;

    status = kstrtou8(buf, 10, &input);
    if (status) {
        return status;
    }

    reg = attribute_mappings[attr->index].reg;
    switch(attr->index)
    {
        /* MEZZ TOP_L */
        case MODULE_PRESENT_1 ... MODULE_PRESENT_16:
        case MODULE_LPMODE_1 ... MODULE_LPMODE_16:
        case MODULE_RESET_1 ... MODULE_RESET_16:
            fpga_spi_mux_data = 0x04;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            bit_mask = 0x01 << port_index;
            break;

        /* MEZZ TOP_R */
        case MODULE_PRESENT_17 ... MODULE_PRESENT_32:
        case MODULE_LPMODE_17 ... MODULE_LPMODE_32:
        case MODULE_RESET_17 ... MODULE_RESET_32:
            fpga_spi_mux_data = 0x05;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            bit_mask = 0x01 << port_index;
            break;

        /* MB CPLD0 */
        case MODULE_PRESENT_33 ... MODULE_PRESENT_48:
        case MODULE_LPMODE_33 ... MODULE_LPMODE_48:
        case MODULE_RESET_33 ... MODULE_RESET_48:
            fpga_spi_mux_data = 0x00;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            if (port_index < 2)
                bit_mask = 0x01 << port_index;
            else
                bit_mask = 0x01 << (port_index + 2);
            break;

        /* MB CPLD1 */
        case MODULE_PRESENT_49 ... MODULE_PRESENT_64:
        case MODULE_LPMODE_49 ... MODULE_LPMODE_64:
        case MODULE_RESET_49 ... MODULE_RESET_64:
            fpga_spi_mux_data = 0x01;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            if (port_index < 2)
                bit_mask = 0x01 << port_index;
            else
                bit_mask = 0x01 << (port_index + 2);
            break;

        /* MB CPLD0 */
        case MODULE_PRESENT_65 ... MODULE_PRESENT_80:
        case MODULE_LPMODE_65 ... MODULE_LPMODE_80:
        case MODULE_RESET_65 ... MODULE_RESET_80:
            fpga_spi_mux_data = 0x00;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            if (port_index < 2)
                bit_mask = 0x01 << (port_index + 2);
            else
                bit_mask = 0x01 << (port_index + 4);
            break;

        /* MB CPLD1 */
        case MODULE_PRESENT_81 ... MODULE_PRESENT_96:
        case MODULE_LPMODE_81 ... MODULE_LPMODE_96:
        case MODULE_RESET_81 ... MODULE_RESET_96:
            fpga_spi_mux_data = 0x01;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            if (port_index < 2)
                bit_mask = 0x01 << (port_index + 2);
            else
                bit_mask = 0x01 << (port_index + 4);
            break;

        /* MEZZ BOT_L */
        case MODULE_PRESENT_97 ... MODULE_PRESENT_112:
        case MODULE_LPMODE_97 ... MODULE_LPMODE_112:
        case MODULE_RESET_97 ... MODULE_RESET_112:
            fpga_spi_mux_data = 0x02;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            bit_mask = 0x01 << port_index;
            break;

        /* MEZZ BOT_R */
        case MODULE_PRESENT_113 ... MODULE_PRESENT_128:
        case MODULE_LPMODE_113 ... MODULE_LPMODE_128:
        case MODULE_RESET_113 ... MODULE_RESET_128:
            fpga_spi_mux_data = 0x03;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            bit_mask = 0x01 << port_index;
            break;

        /* SFP 129-130 (MB CPLD1) */
        case MODULE_PRESENT_129 ... MODULE_PRESENT_130:
        case MODULE_TX_DISABLE_129 ... MODULE_TX_DISABLE_130:
        case MODULE_RX_LOS_129 ... MODULE_RX_LOS_130:
        case MODULE_TX_FAULT_129 ... MODULE_TX_FAULT_130:
            fpga_spi_mux_data = 0x01;
            port_index = attr->index - attribute_mappings[attr->index].attr_base;
            bit_mask = 0x01 << port_index;
            break;

        default:
            break;
    }

    spi_mask = SPI_BUSY_MASK_CPLD;
    addr = fpga_ctl->pci_fpga_dev.data_base_addr0;

    bit_mask = 0x01 << (attr->index - attribute_mappings[attr->index].attr_base);
    should_set_bit = attribute_mappings[attr->index].revert ? !input : input;

    LOCK(&cpld_access_lock);
    iowrite8(fpga_spi_mux_data, spi_mux_reg);
    reg_val = fpga_read(addr + reg, spi_mask);
    if (should_set_bit) {
        reg_val |= bit_mask;
    } else {
        reg_val &= ~bit_mask;
    }
    fpga_write(addr + reg, reg_val, spi_mask);
    UNLOCK(&cpld_access_lock);

    return count;
}

struct _port_data {
    u16 offset;
    u16 mask; /* SPI Busy mask : 0x01 --> CPLD1, 0x02 --> CPLD2 */
};
/* ============PCIe Bar Offset to I2C Master Mapping============== */
static const struct _port_data port[PORT_NUM]= {
    /* QSFP Port 0-15, Region 5, PCIE to MEZZ_CPLD0 */
    {0x2100, SPI_BUSY_MASK_CPLD},/* 0x2100 - 0x2110  I2C Master OSFP Port0 */
    {0x2120, SPI_BUSY_MASK_CPLD},/* 0x2120 - 0x2130  I2C Master OSFP Port1 */
    {0x2140, SPI_BUSY_MASK_CPLD},/* 0x2140 - 0x2150  I2C Master OSFP Port2 */
    {0x2160, SPI_BUSY_MASK_CPLD},/* 0x2160 - 0x2170  I2C Master OSFP Port3 */
    {0x2180, SPI_BUSY_MASK_CPLD},/* 0x2180 - 0x2190  I2C Master OSFP Port4 */
    {0x21A0, SPI_BUSY_MASK_CPLD},/* 0x21A0 - 0x21B0  I2C Master OSFP Port5 */
    {0x21C0, SPI_BUSY_MASK_CPLD},/* 0x21C0 - 0x21D0  I2C Master OSFP Port6 */
    {0x21E0, SPI_BUSY_MASK_CPLD},/* 0x21E0 - 0x21F0  I2C Master OSFP Port7 */
    {0x2200, SPI_BUSY_MASK_CPLD},/* 0x2200 - 0x2210  I2C Master OSFP Port8 */
    {0x2220, SPI_BUSY_MASK_CPLD},/* 0x2220 - 0x2230  I2C Master OSFP Port9 */
    {0x2240, SPI_BUSY_MASK_CPLD},/* 0x2240 - 0x2250  I2C Master OSFP Port10 */
    {0x2260, SPI_BUSY_MASK_CPLD},/* 0x2260 - 0x2270  I2C Master OSFP Port11 */
    {0x2280, SPI_BUSY_MASK_CPLD},/* 0x2280 - 0x2290  I2C Master OSFP Port12 */
    {0x22A0, SPI_BUSY_MASK_CPLD},/* 0x22A0 - 0x22B0  I2C Master OSFP Port13 */
    {0x22C0, SPI_BUSY_MASK_CPLD},/* 0x22C0 - 0x22D0  I2C Master OSFP Port14 */
    {0x22E0, SPI_BUSY_MASK_CPLD},/* 0x22E0 - 0x22F0  I2C Master OSFP Port15 */
    /* QSFP Port 16-31, Region 5, PCIE to MEZZ_CPLD2 */
    {0x2100, SPI_BUSY_MASK_CPLD},/* 0x2100 - 0x2110  I2C Master OSFP Port16 */
    {0x2120, SPI_BUSY_MASK_CPLD},/* 0x2120 - 0x2130  I2C Master OSFP Port17*/
    {0x2140, SPI_BUSY_MASK_CPLD},/* 0x2140 - 0x2150  I2C Master OSFP Port18 */
    {0x2160, SPI_BUSY_MASK_CPLD},/* 0x2160 - 0x2170  I2C Master OSFP Port19 */
    {0x2180, SPI_BUSY_MASK_CPLD},/* 0x2180 - 0x2190  I2C Master OSFP Port20 */
    {0x21A0, SPI_BUSY_MASK_CPLD},/* 0x21A0 - 0x21B0  I2C Master OSFP Port21 */
    {0x21C0, SPI_BUSY_MASK_CPLD},/* 0x21C0 - 0x21D0  I2C Master OSFP Port22 */
    {0x21E0, SPI_BUSY_MASK_CPLD},/* 0x21E0 - 0x21F0  I2C Master OSFP Port23 */
    {0x2200, SPI_BUSY_MASK_CPLD},/* 0x2200 - 0x2210  I2C Master OSFP Port24 */
    {0x2220, SPI_BUSY_MASK_CPLD},/* 0x2220 - 0x2230  I2C Master OSFP Port25 */
    {0x2240, SPI_BUSY_MASK_CPLD},/* 0x2240 - 0x2250  I2C Master OSFP Port26 */
    {0x2260, SPI_BUSY_MASK_CPLD},/* 0x2260 - 0x2270  I2C Master OSFP Port27 */
    {0x2280, SPI_BUSY_MASK_CPLD},/* 0x2280 - 0x2290  I2C Master OSFP Port28 */
    {0x22A0, SPI_BUSY_MASK_CPLD},/* 0x22A0 - 0x22B0  I2C Master OSFP Port29 */
    {0x22C0, SPI_BUSY_MASK_CPLD},/* 0x22C0 - 0x22D0  I2C Master OSFP Port30 */
    {0x22E0, SPI_BUSY_MASK_CPLD},/* 0x22E0 - 0x22F0  I2C Master OSFP Port31 */
    /* QSFP Port 32-47, Region 5, PCIE to MEZZ_CPLD1 */
    {0x2100, SPI_BUSY_MASK_CPLD},/* 0x2100 - 0x2110  I2C Master OSFP Port32 */
    {0x2120, SPI_BUSY_MASK_CPLD},/* 0x2120 - 0x2130  I2C Master OSFP Port33 */
    {0x2140, SPI_BUSY_MASK_CPLD},/* 0x2140 - 0x2150  I2C Master OSFP Port34 */
    {0x2160, SPI_BUSY_MASK_CPLD},/* 0x2160 - 0x2170  I2C Master OSFP Port35 */
    {0x2180, SPI_BUSY_MASK_CPLD},/* 0x2180 - 0x2190  I2C Master OSFP Port36 */
    {0x21A0, SPI_BUSY_MASK_CPLD},/* 0x21A0 - 0x21B0  I2C Master OSFP Port37 */
    {0x21C0, SPI_BUSY_MASK_CPLD},/* 0x21C0 - 0x21D0  I2C Master OSFP Port38 */
    {0x21E0, SPI_BUSY_MASK_CPLD},/* 0x21E0 - 0x21F0  I2C Master OSFP Port39 */
    {0x2200, SPI_BUSY_MASK_CPLD},/* 0x2200 - 0x2210  I2C Master OSFP Port40 */
    {0x2220, SPI_BUSY_MASK_CPLD},/* 0x2220 - 0x2230  I2C Master OSFP Port41 */
    {0x2240, SPI_BUSY_MASK_CPLD},/* 0x2240 - 0x2250  I2C Master OSFP Port42 */
    {0x2260, SPI_BUSY_MASK_CPLD},/* 0x2260 - 0x2270  I2C Master OSFP Port43 */
    {0x2280, SPI_BUSY_MASK_CPLD},/* 0x2280 - 0x2290  I2C Master OSFP Port44 */
    {0x22A0, SPI_BUSY_MASK_CPLD},/* 0x22A0 - 0x22B0  I2C Master OSFP Port45 */
    {0x22C0, SPI_BUSY_MASK_CPLD},/* 0x22C0 - 0x22D0  I2C Master OSFP Port46 */
    {0x22E0, SPI_BUSY_MASK_CPLD},/* 0x22E0 - 0x22F0  I2C Master OSFP Port47 */
    /* OSFP Port48-59, Region 4, PCIE to MB_CPLD0 */
    {0x2100, SPI_BUSY_MASK_CPLD},/* 0x2100 - 0x2110  I2C Master OSFP Port48 */
    {0x2120, SPI_BUSY_MASK_CPLD},/* 0x2120 - 0x2130  I2C Master OSFP Port49 */
    {0x2140, SPI_BUSY_MASK_CPLD},/* 0x2140 - 0x2150  I2C Master OSFP Port50 */
    {0x2160, SPI_BUSY_MASK_CPLD},/* 0x2160 - 0x2170  I2C Master OSFP Port51 */
    {0x2180, SPI_BUSY_MASK_CPLD},/* 0x2180 - 0x2190  I2C Master OSFP Port52 */
    {0x21A0, SPI_BUSY_MASK_CPLD},/* 0x21A0 - 0x21B0  I2C Master OSFP Port53 */
    {0x21C0, SPI_BUSY_MASK_CPLD},/* 0x21C0 - 0x21D0  I2C Master OSFP Port54 */
    {0x21E0, SPI_BUSY_MASK_CPLD},/* 0x21E0 - 0x21F0  I2C Master OSFP Port55 */
    {0x2200, SPI_BUSY_MASK_CPLD},/* 0x2200 - 0x2210  I2C Master OSFP Port56 */
    {0x2220, SPI_BUSY_MASK_CPLD},/* 0x2220 - 0x2230  I2C Master OSFP Port57 */
    {0x2240, SPI_BUSY_MASK_CPLD},/* 0x2240 - 0x2250  I2C Master OSFP Port58 */
    {0x2260, SPI_BUSY_MASK_CPLD},/* 0x2260 - 0x2270  I2C Master OSFP Port59 */
    /* OSFP Port60-71, Region 4, PCIE to MB_CPLD1 */
    {0x2100, SPI_BUSY_MASK_CPLD},/* 0x2100 - 0x2110  I2C Master OSFP Port60 */
    {0x2120, SPI_BUSY_MASK_CPLD},/* 0x2120 - 0x2130  I2C Master OSFP Port61 */
    {0x2140, SPI_BUSY_MASK_CPLD},/* 0x2140 - 0x2150  I2C Master OSFP Port62 */
    {0x2160, SPI_BUSY_MASK_CPLD},/* 0x2160 - 0x2170  I2C Master OSFP Port63 */
    {0x2180, SPI_BUSY_MASK_CPLD},/* 0x2180 - 0x2190  I2C Master OSFP Port64 */
    {0x21A0, SPI_BUSY_MASK_CPLD},/* 0x21A0 - 0x21B0  I2C Master OSFP Port65 */
    {0x21C0, SPI_BUSY_MASK_CPLD},/* 0x21C0 - 0x21D0  I2C Master OSFP Port66 */
    {0x21E0, SPI_BUSY_MASK_CPLD},/* 0x21E0 - 0x21F0  I2C Master OSFP Port67 */
    {0x2200, SPI_BUSY_MASK_CPLD},/* 0x2200 - 0x2210  I2C Master OSFP Port68 */
    {0x2220, SPI_BUSY_MASK_CPLD},/* 0x2220 - 0x2230  I2C Master OSFP Port69 */
    {0x2240, SPI_BUSY_MASK_CPLD},/* 0x2240 - 0x2250  I2C Master OSFP Port70 */
    {0x2260, SPI_BUSY_MASK_CPLD},/* 0x2260 - 0x2270  I2C Master OSFP Port71 */
    /* SFP port 72-75, Region 5, PCIE to MEZZ_CPLD1 */
    {0x2300, SPI_BUSY_MASK_CPLD},/* 0x2300 - 0x2310  I2C Master SFP+ Port72 */
    {0x2320, SPI_BUSY_MASK_CPLD},/* 0x2320 - 0x2330  I2C Master SFP+ Port73 */
    {0x2340, SPI_BUSY_MASK_CPLD},/* 0x2340 - 0x2350  I2C Master SFP+ Port74 */
    {0x2360, SPI_BUSY_MASK_CPLD},/* 0x2360 - 0x2370  I2C Master SFP+ Port75 */

};

static struct ocores_i2c_platform_data as1813_128_platform_data = {
    .reg_io_width = 1,
    .reg_shift = 2,
    /*
     * PRER_L and PRER_H are calculated based on clock_khz and bus_khz
     * in i2c-ocores.c:ocores_init.
     */
#if 1
    /* SCL 400KHZ in FPGA spec. => PRER_L = 0x0B, PRER_H = 0x00 */
    .clock_khz = 24000,
    //.bus_khz = 400,
#else
    /* SCL 100KHZ in FPGA spec. => PRER_L = 0x2F, PRER_H = 0x00 */
    .clock_khz = 24000,
    .bus_khz = 100,
#endif
};

struct platform_device *ocore_i2c_device_add(unsigned int id, unsigned long bar_base,
                                             unsigned int offset)
{
    struct resource res = DEFINE_RES_MEM(bar_base + offset, 0x20);
    struct platform_device *pdev;
    int err;

    pdev = platform_device_alloc(OCORES_I2C_DRVNAME, id);
    if (!pdev) {
        err = -ENOMEM;
        pcie_err("Port%u device allocation failed (%d)\n", (id & 0xFF), err);
        goto exit;
    }

    err = platform_device_add_resources(pdev, &res, 1);
    if (err) {
        pcie_err("Port%u device resource addition failed (%d)\n", (id & 0xFF), err);
        goto exit_device_put;
    }

    err = platform_device_add_data(pdev, &as1813_128_platform_data,
                       sizeof(struct ocores_i2c_platform_data));
    if (err) {
        pcie_err("Port%u platform data allocation failed (%d)\n", (id & 0xFF), err);
        goto exit_device_put;
    }

    err = platform_device_add(pdev);
    if (err) {
        pcie_err("Port%u device addition failed (%d)\n", (id & 0xFF), err);
        goto exit_device_put;
    }

    return pdev;

exit_device_put:
    platform_device_put(pdev);
exit:
    return NULL;
}

static int as1813_128_pcie_fpga_stat_probe(struct platform_device *pdev)
{
    struct device *dev = &pdev->dev;
    struct as1813_128_fpga_data *fpga_ctl;
    struct pci_dev *pcidev;
    struct resource *ret;
    int i;
    int status = 0, err = 0;
    unsigned long bar_base;
    int fpga_spi_mux_data;

    fpga_ctl = devm_kzalloc(dev, sizeof(struct as1813_128_fpga_data), GFP_KERNEL);
    if (!fpga_ctl) {
        return -ENOMEM;
    }
    platform_set_drvdata(pdev, fpga_ctl);

    pcidev = pci_get_device(FPGA_PCI_VENDOR_ID, FPGA_PCI_DEVICE_ID, NULL);
     if (!pcidev) {
        dev_err(dev, "Cannot found PCI device(%x:%x)\n",
                     FPGA_PCI_VENDOR_ID, FPGA_PCI_DEVICE_ID);
        return -ENODEV;
    }
    fpga_ctl->pci_fpga_dev.pci_dev = pcidev;

    err = pci_enable_device(pcidev);
    if (err != 0) {
        dev_err(dev, "Cannot enable PCI device(%x:%x)\n",
                     FPGA_PCI_VENDOR_ID, FPGA_PCI_DEVICE_ID);
        status = -ENODEV;
        goto exit_pci_disable;
    }
    /* enable PCI bus-mastering */
    pci_set_master(pcidev);

    /*
     * Detect platform for changing the setting behavior of LP mode.
     */
    fpga_ctl->pci_fpga_dev.data_base_addr0 = pci_iomap(pcidev, BAR0_NUM, 0);
    if (fpga_ctl->pci_fpga_dev.data_base_addr0 == NULL) {
        dev_err(dev, "Failed to map BAR0\n");
        status = -EIO;
        goto exit_pci_disable;
    }

    spi_busy_reg = fpga_ctl->pci_fpga_dev.data_base_addr0 + SPI_BUSY_REG;
    spi_mux_reg = fpga_ctl->pci_fpga_dev.data_base_addr0 + SPI_MUX_REG;

    /* Create I2C ocore devices first, then create the FPGA sysfs.
     * To prevent the application from accessing an ocore device
     * that has not been fully created due to the port status
     * being present.
     */

    /*
     * Create ocore_i2c device for OSFP EEPROM
     */
    for (i = 0; i < PORT_NUM; i++) {
        switch (i)
        {
            case 0 ... 15:
                /* 8'h04: pcie to Mezz_TOP_L */
                fpga_spi_mux_data = 0x04;
                break;
            case 16 ... 31:
                /* 8'h05: pcie to Mezz_TOP_R */
                fpga_spi_mux_data = 0x05;
                break;
            case 32 ... 47:
                /* 8'h00: pcie to MB_CPLD0 */
                fpga_spi_mux_data = 0x00;
                break;
            case 48 ... 63:
                /* 8'h01: pcie to MB_CPLD1 */
                fpga_spi_mux_data = 0x01;
                break;
            case 64 ... 79:
                /* 8'h00: pcie to MB_CPLD0 */
                fpga_spi_mux_data = 0x00;
                break;
            case 80 ... 95:
                /* 8'h01: pcie to MB_CPLD1 */
                fpga_spi_mux_data = 0x01;
                break;
            case 96 ... 111:
                /* 8'h02: pcie to Mezz_BOT_L */
                fpga_spi_mux_data = 0x02;
                break;
            case 112 ... 127:
                /* 8'h03: pcie to Mezz_BOT_R */
                fpga_spi_mux_data = 0x03;
                break;
            case 128 ... 129:
                /* 8'h01: pcie to MB_CPLD1 */
                fpga_spi_mux_data = 0x01;
                break;
            default:
                break;
        }

        bar_base = pci_resource_start(pcidev, BAR0_NUM);
        iowrite8(fpga_spi_mux_data, spi_mux_reg);

        fpga_ctl->pci_fpga_dev.fpga_i2c[i] =
            ocore_i2c_device_add((i | (port[i].mask << 8)), bar_base, port[i].offset);
        if (IS_ERR(fpga_ctl->pci_fpga_dev.fpga_i2c[i])) {
            status = PTR_ERR(fpga_ctl->pci_fpga_dev.fpga_i2c[i]);
            dev_err(dev, "rc:%d, unload Port%u[0x%ux] device\n",
                         status, i, port[i].offset);
            goto exit_ocores_device;
        }
    }

    status = sysfs_create_group(&pdev->dev.kobj, &fpga_port_stat_group);
    if (status) {
        goto exit_ocores_device;
    }

    return 0;

exit_ocores_device:
    while (i > 0) {
        i--;
        platform_device_unregister(fpga_ctl->pci_fpga_dev.fpga_i2c[i]);
    }
exit_pci_iounmap0:
    spi_busy_reg = NULL;
    pci_iounmap(fpga_ctl->pci_fpga_dev.pci_dev, fpga_ctl->pci_fpga_dev.data_base_addr0);
exit_pci_disable:
    pci_disable_device(fpga_ctl->pci_fpga_dev.pci_dev);

    return status;
}

static int as1813_128_pcie_fpga_stat_remove(struct platform_device *pdev)
{
    struct as1813_128_fpga_data *fpga_ctl = platform_get_drvdata(pdev);

    if (pci_is_enabled(fpga_ctl->pci_fpga_dev.pci_dev)) {
        int i;

        sysfs_remove_group(&pdev->dev.kobj, &fpga_port_stat_group);
        /* Unregister ocore_i2c device */
        for (i = 0; i < PORT_NUM; i++) {
            platform_device_unregister(fpga_ctl->pci_fpga_dev.fpga_i2c[i]);
        }
        spi_busy_reg = NULL;
        pci_iounmap(fpga_ctl->pci_fpga_dev.pci_dev, fpga_ctl->pci_fpga_dev.data_base_addr0);
        pci_disable_device(fpga_ctl->pci_fpga_dev.pci_dev);
    }

    return 0;
}

static struct platform_driver pcie_fpga_port_stat_driver = {
    .probe      = as1813_128_pcie_fpga_stat_probe,
    .remove     = as1813_128_pcie_fpga_stat_remove,
    .driver     = {
        .owner = THIS_MODULE,
        .name  = DRVNAME,
    },
};

static int __init as1813_128_pcie_fpga_init(void)
{
    int status = 0;

    /*
     * Create FPGA platform driver and device
     */
    status = platform_driver_register(&pcie_fpga_port_stat_driver);
    if (status < 0) {
        return status;
    }

    pdev = platform_device_register_simple(DRVNAME, -1, NULL, 0);
    if (IS_ERR(pdev)) {
        status = PTR_ERR(pdev);
        goto exit_pci;
    }

    return status;

exit_pci:
    platform_driver_unregister(&pcie_fpga_port_stat_driver);

    return status;
}

static void __exit as1813_128_pcie_fpga_exit(void)
{
    platform_device_unregister(pdev);
    platform_driver_unregister(&pcie_fpga_port_stat_driver);
}


module_init(as1813_128_pcie_fpga_init);
module_exit(as1813_128_pcie_fpga_exit);

MODULE_AUTHOR("Eric Yang <eric_yang@accton.com>");
MODULE_DESCRIPTION("AS1813-128O/AS1813-128D FPGA via PCIE");
MODULE_LICENSE("GPL");
